(SIMP-8377) Updated NFS documentation
simp/simp-doc pull request #389
Opened 2020-10-07 12:54 UTC by trevor-vaughan

Added:
  * Modified the NFS documentation to warn about breaking changes in
    version 7 of simp-nfs and simp-autofs
Fixed:
  * Fixed some code examples
  * Directly linked to SIMP support tickets
Notes:
  * Validated that the NFS and Autofs updates in the changelog for 6.5.0
    reflect the breaking changes well

SIMP-8377 #close

2020-10-07 14:22 UTC, lnemsick-simp requested changes
Looks like hostnames need to be changed to IP addresses as well.  I will fix.

2020-10-07 14:22 UTC, lnemsick-simp commented on docs/user_guide/HOWTO/NFS.rst
> +   are not working properly at this time. See `SIMP-2944`_ for additional
This has been fixed.  I will fix here.

2020-10-07 19:43 UTC, lnemsick-simp commented
Many more changes are required, because simp-nfs now supports direct, indirect, and indirect with wild card autofs mounts

2020-10-07 19:56 UTC, lnemsick-simp commented
I will remove the WIP when I get all the updates in place.

2020-10-08 19:12 UTC, lnemsick-simp commented
There were enough changes that an independent review is warranted.  A separate ticket has been created for the verification.

2020-10-14 17:29 UTC, jeannegreulich approved these changes

2020-10-14 17:29 UTC, merged